version: "3"
services:
    python-dev:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - .:/usr/src/app
        command: src/main.py
        # command: run.sh
